// packages/preact/src/hooks.tsx
import { signal } from "@preact/signals";
import { useEffect } from "preact/hooks";

export const useIsDocumentHidden = () => {
  const isDocumentHidden = signal(
    typeof document !== "undefined" ? document.hidden : false
  );

  useEffect(() => {
    const callback = () => {
      isDocumentHidden.value = document.hidden;
    };
    document.addEventListener("visibilitychange", callback);
    return () =>
      document.removeEventListener("visibilitychange", callback);
  }, []);

  return isDocumentHidden;
};

// packages/solid/src/hooks.tsx
import { createSignal, onCleanup, onMount } from "solid-js";

export const useIsDocumentHidden = () => {
	const [isDocumentHidden, setIsDocumentHidden] = createSignal(
		typeof document !== "undefined" ? document.hidden : false,
	);

	onMount(() => {
		const callback = () => {
			setIsDocumentHidden(document.hidden);
		};
		document.addEventListener("visibilitychange", callback);
		onCleanup(() => document.removeEventListener("visibilitychange", callback));
	});

	return isDocumentHidden;
};
